### ISSUE TITLE
will not print json to .txt

### ISSUE THREAD

**Issue by webcoderz** [justinlittman/fbarc#3]
it only dumps json to terminal, so there is not json file to pass to the graphing

**Comment by justinlittman** [comment]
You can redirect it to a file. For example: `python fbarc.py --debug graph page MarkRWarner --levels 5 > MarkRWarner.jsonl`

Does that solve the problem?

**Comment by webcoderz** [comment]
let me try that
thanks

**Comment by webcoderz** [comment]
yea awesome thanks , can you update that into the readme? is it same way to do it to text and csv and gephx?

**Comment by webcoderz** [comment]
and also when it generates the local server its giving me an internal service error

**Comment by webcoderz** [comment]
and the generated html pages are blank.  when running  python fbarc.py graph page MarkRWarner --levels 5 > MarkRWarner.html
